# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
'''
Your Code
'''

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [4]:
A = np.random.random((5, 5))
A_mean = A.mean()
A_std = A.std()
A_norm = (A - A_mean) / A_std
print(A)
print(A_norm)

[[0.80852669 0.71126541 0.61580215 0.34905108 0.16534214]
 [0.35006283 0.75931815 0.35062036 0.47029876 0.00884797]
 [0.04430463 0.39056328 0.23239612 0.25802973 0.44263844]
 [0.55451042 0.43915887 0.69191809 0.8686979  0.41387954]
 [0.62065614 0.14327542 0.55716261 0.95344722 0.11831347]]
[[ 1.39660051  1.01483001  0.64011716 -0.40693551 -1.12803075]
 [-0.40296417  1.2034469  -0.40077576  0.06898652 -1.74230249]
 [-1.60312782 -0.24399159 -0.86483014 -0.76421297 -0.0395859 ]
 [ 0.39953456 -0.05324393  0.93888784  1.63278485 -0.15247049]
 [ 0.65917005 -1.21464717  0.40994492  1.96544329 -1.31262793]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [5]:
B = np.random.randint(100, size=10)
print(B)
B_max = B.max()
B[B==B_max] = -1
print(B)

[23 92 17 43 68 71 65 10 33 22]
[23 -1 17 43 68 71 65 10 33 22]


In [ ]:
'''
Your Code
'''

[ 0.29347583  0.59303277 -1.          0.38043546  0.63265939  0.32472618
  0.11340241  0.68136955  0.89905432  0.74769935]
